const Joi = require("joi");

const formSchema = Joi.object({
  ben: Joi.string().required(),
  userId: Joi.string().required(),
  firstName: Joi.string().required(),
  lastName: Joi.string().required(),
  birthDate: Joi.date().iso().required(),
  Email: Joi.string().email().required(),
  socialSecurityNo: Joi.string().length(9).pattern(/^[0-9]+$/).required(),
  referringAgency: Joi.string().allow(""),
  treatmentCenter: Joi.string().allow(""),
  driversLicenseNo: Joi.string().allow(""),
  stateIssued: Joi.string().allow(""),
  lastResidence: Joi.string().required(),
  maritalStatus: Joi.string().valid("Single", "Married", "Divorced").required(),
  numberOfChildren: Joi.number().integer().min(0).required(),
  nextOfKin: Joi.string().required(),
  nextOfKinAddress: Joi.string().required(),
  nextOfKinPhone: Joi.string().pattern(/^\d{10}$/).required(),
  emergencyContact: Joi.string().required(),
  emergencyContactAddress: Joi.string().required(),
  emergencyContactPhone: Joi.string().pattern(/^\d{10}$/).required(),
  medicalProblems: Joi.string().required(),
  medicalMedication: Joi.string().required(),
  psychiatricDisorder: Joi.string().required(),
  psychiatricMedication: Joi.string().required(),
  alcoholDrugHistory: Joi.string().allow(""),
  primaryDrugsUsed: Joi.string().allow(""),
  treatmentAttendance: Joi.string().allow(""),
  education: Joi.string().allow(""),
  militaryService: Joi.string().allow(""),
  employmentHistory: Joi.string().allow(""),
  incarcerationHistory: Joi.string().allow(""),
  currentPendingCharges: Joi.string().allow(""),
  pastConvictions: Joi.string().allow(""),
  probationParole: Joi.string().valid("Yes", "No").allow(""),
  probationOfficerName: Joi.string().allow(""),
  probationOfficerPhone: Joi.string().pattern(/^\d{10}$/).allow(""),
  lastCompanyName: Joi.string().allow(""),
  lastCompanyAddress: Joi.string().allow(""),
  employmentFrom: Joi.date().iso().allow(""),
  employmentTo: Joi.date().iso().allow(""),
  reasonForLeaving: Joi.string().allow(""),
  numberOfJobsInLastFiveYears: Joi.number().integer().min(0).allow(""),
  futureEmploymentPlans: Joi.string().allow(""),
  jobSkills: Joi.string().allow(""),
  numberOfSchoolsAttended: Joi.number().integer().min(0).allow(""),
  schoolPlace: Joi.string().allow(""),
  schoolYear: Joi.date().iso().allow(""),
  lastGradeCompleted: Joi.string().allow(""),
  collegeTradeSchoolDegree: Joi.string().allow(""),
  servedInMilitary: Joi.string().valid("Yes", "No").allow(""),
  militaryYears: Joi.number().integer().min(0).allow(""),
  militaryBranch: Joi.string().allow(""),
  typeOfDischarge: Joi.string().allow(""),
  everIncarcerated: Joi.string().valid("Yes", "No").allow(""), 
});

module.exports = formSchema;